<?php

namespace AppBundle\Repository;

/**
 * AmministratoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmministratoreRepository extends \Doctrine\ORM\EntityRepository
{
}
