<?php

namespace AppBundle\Repository;

/**
 * AppartenereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartenereRepository extends \Doctrine\ORM\EntityRepository
{
}
