<?php

namespace AppBundle\Repository;

/**
 * ClientiEsterniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientiEsterniRepository extends \Doctrine\ORM\EntityRepository
{
}
