<?php

namespace AppBundle\Repository;

/**
 * GraficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraficoRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkUsername($em,$user){
        
        $p = $em->getRepository("AppBundle:Grafico")->findOneBy(array("username"=>$user,));
        if(!$p) {
            return(FALSE); //cos'è p
        }else {return TRUE;}
    }
    
    public function getIdByUsername($em,$user){
        $query = $em->createQuery(
            'SELECT g.id
            FROM AppBundle:Grafico g
            WHERE g.username = :user'
        )->setParameter('user', $user);
        return($query->getSingleScalarResult());
    }
    
    public function tabellaEseguire($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query = $em->createQuery(
            'SELECT c.Nome, c.Cognome, o.id, o.Data
            FROM Appbundle:Ordine o, AppBundle:Cliente c, AppBundle:Grafica g
            WHERE c.id = o.ClienteId AND o.GraficaId = g.id AND (o.StatoId = 9 AND g.GraficoId = :id)' 
        )->setParameter('id', $id); 

        $eseguire = $query->setMaxResults($n)->getResult();
        return $eseguire;

    }
    
    public function tabellaInLavorazione($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query = $em->createQuery(
            'SELECT c.Nome, c.Cognome, o.id, e.Data
            FROM Appbundle:Ordine o, AppBundle:Cliente c, AppBundle:Grafica g, AppBundle:EventoGrafica e
            WHERE c.id = o.ClienteId AND o.GraficaId = g.id AND (g.GraficoId = :id AND o.StatoId = 10)' 
        )->setParameter('id', $id);
        
        $lavorazione = $query->setMaxResults($n)->getResult();
        return $lavorazione;

    }
    
    public function tabellaDaRieseguire ($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query = $em->createQuery(
            'SELECT c.Nome, c.Cognome, o.id, o.Data
            FROM Appbundle:Ordine o, AppBundle:Cliente c, AppBundle:Grafica g
            WHERE c.id = o.ClienteId AND o.GraficaId = g.id AND (g.GraficoId = :id AND o.StatoId = 12)' 
        )->setParameter('id', $id);
        
        $rieseguire = $query->setMaxResults($n)->getResult();
        return $rieseguire;

    }
    
    public function tabellaInAttesa ($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);   
        $query = $em->createQuery(
            'SELECT c.Nome, c.Cognome, o.id, o.Data
            FROM Appbundle:Ordine o, AppBundle:Cliente c, AppBundle:Grafica g
            WHERE c.id = o.ClienteId AND o.GraficaId = g.id AND (o.StatoId = 11 AND g.GraficoId = 0)' 
        )->setParameter('id', $id);
        
        $attesa = $query->setMaxResults($n)->getResult();
        return $attesa;
        
    }


}