<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;


/**
 * GraficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraficoRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkUsername($em,$user){
        
        $p = $em->getRepository("AppBundle:Grafico")->findOneBy(array("username"=>$user,));
        if(!$p) {
            return(FALSE); //cos'è p
        }else {return TRUE;}
    }
    
    public function getIdByUsername($em,$user){
        $query = $em->createQuery(
            'SELECT g.id
            FROM AppBundle:Grafico g
            WHERE g.username = :user '
        )->setParameter('user', $user);
        return($query->getSingleScalarResult());
    }
    
    public function tabellaEseguire($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query='
            SELECT odp.codicecliente as cliente, odp.codiceordine as codicelavorazione, odp.data as data 
            FROM OrdineDatiPrincipali odp, grafica g
            WHERE odp.idgrafica=g.id and odp.idstato=9 and g.GraficoId='.$id.'
            Limit '.$n;
        
        $stmt = $em->getConnection()->prepare($query);
        $stmt->execute();
        return $stmt->fetchAll();

    }
    
    public function tabellaInLavorazione($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query='
            SELECT odp.codicecliente as cliente, odp.codiceordine as codicelavorazione, odp.data as data 
            FROM OrdineDatiPrincipali odp, grafica g
            WHERE odp.idgrafica=g.id and odp.idstato=10 and g.GraficoId='.$id.'
            Limit '.$n;

        $stmt = $em->getConnection()->prepare($query);
        $stmt->execute();
        return $stmt->fetchAll();


    }
    
    public function tabellaDaRieseguire ($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query='
            SELECT odp.codicecliente as cliente, odp.codiceordine as codicelavorazione, odp.data as data 
            FROM OrdineDatiPrincipali odp, grafica g
            WHERE odp.idgrafica=g.id and odp.idstato=12 and g.GraficoId='.$id.'
            Limit '.$n;


        $stmt = $em->getConnection()->prepare($query);
        $stmt->execute();
        return $stmt->fetchAll();

    }
    
    public function tabellaInAttesa ($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query='
            SELECT odp.codicecliente as cliente, odp.codiceordine as codicelavorazione, odp.data as data 
            FROM OrdineDatiPrincipali odp, grafica g
            WHERE odp.idgrafica=g.id and odp.idstato=11 and g.GraficoId='.$id.'
            Limit '.$n;

        $stmt = $em->getConnection()->prepare($query);
        $stmt->execute();
        return $stmt->fetchAll();
        
    }


}
