<?php

namespace AppBundle\Repository;

/**
 * GruppoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruppoRepository extends \Doctrine\ORM\EntityRepository
{
    public function DatiGruppo($em){
        $query=$em->createQuery('   SELECT g.*, count(ga.*) 
                                    FROM AppBundle:gruppo g, AppBundle:gruppo__attributi ga 
                                    WHERE g.id=ga.GruppoId 
                                    GROUP BY g.id'
                );
        return $query->getResult() ;        
    }
    
    public function PrelevaAttributiRequest($request,$numVal){
        for ($c=1; $c<=$numVal; $c++){
            if($request->get($c)){
                $ris[]=$request->get($c);
            }
        }
        return $ris;
    }
    public  function creaGruppo($em,$nome){
        $unGruppo= new \AppBundle\Entity\Gruppo();
        $unGruppo->setNome($nome);
        $em->persist($unGruppo);
        $em->flush();
        return $unGruppo;
    }
    
    public function RicercaFullText($em,$str){
        $str=$str."%"; 
       $query = $em->createQuery(
            'SELECT g.id, g.nome
            FROM AppBundle:Gruppo g
            WHERE g.id LIKE :str or g.nome LIKE :str ' 
        )->setParameter('str',$str);
        $ris = $query->getResult();
        return $ris;
        
    }
    
     public function elimina($em,$idSet){
        $gruppo= $this->find($idSet); 
        $em->remove($gruppo);
        $em->flush();
        return "Cancellazione andata a buon fine";
    }
    
    public function modifica($em,$idGruppo,$nome){
        $unGruppo=  $this->find($idGruppo);
        $unGruppo->setNome($nome);
        $em->flush();
        return "inserimento completato";
    }
}
