<?php

namespace AppBundle\Repository;

/**
 * GruppoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruppoRepository extends \Doctrine\ORM\EntityRepository
{
    public function DatiGruppo($em){
        $query=$em->createQuery('   SELECT g.*, count(ga.*) 
                                    FROM AppBundle:gruppo g, AppBundle:gruppo__attributi ga 
                                    WHERE g.id=ga.GruppoId 
                                    GROUP BY g.id'
                );
        return $query->getResult() ;        
    }
}
