<?php

namespace AppBundle\Repository;

/**
 * OperatoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLavoratori($em, $idRP){
       $query=$em->createQuery('
                    SELECT O.id,O.nome, O.cognome, O.dataNascita, O.codiceFiscale, O.telefono, O.mail, O.username
                    FROM AppBundle:Operatore O, AppBundle:Operatore R
                    WHERE  R.sitoProduzioneId=O.sitoProduzioneId AND O.id<>R.id and R.id=:idRP
                    ')->setParameter('idRP',$idRP);
        $ris = $query->getResult();
        return $ris;
    }
}
