<?php

namespace AppBundle\Repository;

/**
 * OrdiniEsterniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdiniEsterniRepository extends \Doctrine\ORM\EntityRepository
{
}
