<?php

namespace AppBundle\Repository;

/**
 * ValoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoreRepository extends \Doctrine\ORM\EntityRepository
{
     public function RicercaValoriByAttributo($em,$str){
        $query = $em->createQuery(
            'SELECT v.id as idvalore,v.nome as valore
            FROM AppBundle:Valore v
            WHERE v.attributoId=:str' 
        )->setParameter('str',$str);

        $ris = $query->setMaxResults(25)->getResult();
        return $ris;
    }
    
     public function elimina($em,$idAttributo){
        $valori= $this->findBy(array("attributoId"=>$idAttributo));
        foreach ($valori as $x){
            $em->remove($x);
        }
        $em->flush();
        return;
    }
}
